# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main


pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'
  workingDirectory: angular-app/

# - task: ArchiveFiles@2
#   inputs:
#     rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
#     includeRootFolder: true
#     archiveType: zip
    
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

# - task: AzureWebApp@1
#   inputs:
#     azureSubscription: '2dda353d-ea8e-4c76-9e7d-0cbec6f34e5d'
#     appName: 'azure-test-angular'
#     package: '$(System.DefaultWorkingDirectory)'
#     customWebConfig: '-Handler iisnode -NodeStartFile server.js -appType node'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure RD research plan - Ferdi Stoeltie(2dda353d-ea8e-4c76-9e7d-0cbec6f34e5d)'
    appType: webApp
    appName: 'test-angular-ls'
    package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    runtimeStack: 'NODE|12-lts'

# - task: AzureWebApp@1
#   inputs:
#     azureSubscription: 'Azure RD research plan - Ferdi Stoeltie(2dda353d-ea8e-4c76-9e7d-0cbec6f34e5d)'
#     appType: 'webAppLinux'
#     appName: 'azure-test-angular'
#     package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
#     runtimeStack: 'NODE|12-lts'
